import type { CapturedComment, TrendingVideo } from './types'

// ─────────────────────────────────────────────────────────────
// 픽스처 데이터셋
//
// YOUTUBE_API_KEY 가 없을 때 사용하는 대체 데이터입니다.
// 실제 유튜브 영상이 아니라 데모용으로 만든 가상의 영상 목록이며,
// 실제 채널·크리에이터를 지칭하지 않습니다. (id 접두사 fx_)
//
// 길이 필터(3~60분)와 재사용 필터(creativeCommon)를 실제로 검증할 수 있게
// 통과/탈락 케이스를 의도적으로 섞어 두었습니다.
// ─────────────────────────────────────────────────────────────

export const FIXTURE_VIDEOS: TrendingVideo[] = [
  {
    id: 'fx_a1',
    title: '10년 차 편집자가 알려주는 컷 편집의 모든 것 (완전판)',
    channelTitle: '편집실 노트',
    durationSec: 1_842,
    viewCount: 412_000,
    publishedLabel: '2일 전',
    category: '과학·기술',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a2',
    title: '창업 3년 만에 폐업했습니다 — 실패에서 배운 7가지',
    channelTitle: '작은가게 기록',
    durationSec: 2_615,
    viewCount: 1_130_000,
    publishedLabel: '1일 전',
    category: '교육',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a3',
    title: '라면 하나로 끝내는 자취 요리 12가지 몰아보기',
    channelTitle: '자취생 부엌',
    durationSec: 1_265,
    viewCount: 887_400,
    publishedLabel: '3일 전',
    category: '요리·노하우',
    license: 'youtube',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a4',
    title: '전기차 배터리, 왜 겨울에 주행거리가 반토막 날까',
    channelTitle: '테크 브리핑',
    durationSec: 964,
    viewCount: 523_800,
    publishedLabel: '4일 전',
    category: '과학·기술',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a5',
    title: '프로 선수와 아마추어의 스윙 차이 슬로모션 분석',
    channelTitle: '스윙 랩',
    durationSec: 738,
    viewCount: 296_100,
    publishedLabel: '5일 전',
    category: '스포츠',
    license: 'youtube',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a6',
    title: '무인도 3박 4일 생존 브이로그 (풀버전)',
    channelTitle: '한계실험',
    durationSec: 4_380,
    viewCount: 2_040_000,
    publishedLabel: '2일 전',
    category: '엔터테인먼트',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a7',
    title: '중고차 살 때 절대 놓치면 안 되는 체크리스트',
    channelTitle: '차고지 상담소',
    durationSec: 1_105,
    viewCount: 741_200,
    publishedLabel: '6일 전',
    category: '요리·노하우',
    license: 'youtube',
    embeddable: false, // 퍼가기 차단 → 권리 확인에서 탈락
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a8',
    title: '초보자를 위한 홈트 30분 루틴 따라하기',
    channelTitle: '홈트 코치 민',
    durationSec: 1_806,
    viewCount: 388_900,
    publishedLabel: '1일 전',
    category: '스포츠',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a9',
    title: '이 장면 하나로 영화가 완성됐다 (스포일러 주의)',
    channelTitle: '씬 해설',
    durationSec: 152, // 3분 미만 → 길이 필터 탈락
    viewCount: 1_920_000,
    publishedLabel: '1일 전',
    category: '엔터테인먼트',
    license: 'youtube',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a10',
    title: '리그 결승 풀 경기 다시보기 — 5세트 전체',
    channelTitle: '경기 아카이브',
    durationSec: 8_940, // 60분 초과 → 길이 필터 탈락
    viewCount: 3_310_000,
    publishedLabel: '2일 전',
    category: '게임',
    license: 'youtube',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a11',
    title: '신작 게임 4시간 플레이 요약 — 이건 사도 됩니다',
    channelTitle: '겜플 리뷰',
    durationSec: 2_248,
    viewCount: 655_300,
    publishedLabel: '3일 전',
    category: '게임',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a12',
    title: '금리 인하가 내 대출에 미치는 영향 정리',
    channelTitle: '숫자로 보는 경제',
    durationSec: 1_512,
    viewCount: 964_700,
    publishedLabel: '4일 전',
    category: '뉴스·정치',
    license: 'youtube',
    embeddable: true,
    regionBlocked: true, // 지역 차단 → 권리 확인에서 탈락
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a13',
    title: '길거리 인터뷰 100명에게 같은 질문을 했습니다',
    channelTitle: '거리의 목소리',
    durationSec: 1_398,
    viewCount: 1_450_000,
    publishedLabel: '1일 전',
    category: '엔터테인먼트',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
  {
    id: 'fx_a14',
    title: '작곡가가 히트곡 후렴구를 만드는 과정 전체 공개',
    channelTitle: '스튜디오 라이브',
    durationSec: 2_022,
    viewCount: 512_400,
    publishedLabel: '5일 전',
    category: '음악',
    license: 'creativeCommon',
    embeddable: true,
    regionBlocked: false,
    thumbnailUrl: null,
    source: 'fixture',
  },
]

export const FIXTURE_CATEGORIES = [
  '전체',
  '엔터테인먼트',
  '게임',
  '스포츠',
  '음악',
  '뉴스·정치',
  '과학·기술',
  '요리·노하우',
  '교육',
] as const

// 댓글 캡처용 픽스처 댓글 풀.
// 실제 유튜브 댓글이 아니라 데모용으로 작성한 문구입니다.
export const FIXTURE_COMMENTS: CapturedComment[] = [
  { author: '@dohyun_log', text: '이거 진짜 아무도 안 알려주는 내용인데 그냥 다 풀어주네요', likeCount: 3_412, publishedLabel: '2일 전' },
  { author: '@mint_choco77', text: '중간에 나온 그 부분 다시 보러 왔습니다 세 번째임', likeCount: 1_866, publishedLabel: '1일 전' },
  { author: '@서준아빠', text: '와 저도 똑같이 실패했는데 원인이 이거였네요…', likeCount: 2_205, publishedLabel: '3일 전' },
  { author: '@jaein_k', text: '설명 속도 딱 좋아요 배속 안 해도 되는 영상 오랜만', likeCount: 987, publishedLabel: '2일 전' },
  { author: '@노란고양이', text: '이 채널 왜 이제야 떴는지 이해가 안 됨', likeCount: 4_530, publishedLabel: '1일 전' },
  { author: '@yeonwoo.dev', text: '결론 부분만 세 번 돌려봤어요 저장 필수', likeCount: 1_402, publishedLabel: '4일 전' },
  { author: '@hyun_2', text: '반박하려고 봤는데 그냥 납득했습니다', likeCount: 2_781, publishedLabel: '2일 전' },
  { author: '@담백한하루', text: '이런 거 무료로 봐도 되는 건가 싶은 영상', likeCount: 3_055, publishedLabel: '5일 전' },
  { author: '@minsoo_park', text: '타임스탬프 남겨주신 분 감사합니다 진심', likeCount: 741, publishedLabel: '3일 전' },
  { author: '@bboya', text: '저 부분에서 소리 질렀어요 ㅋㅋㅋㅋ 예상 못 했음', likeCount: 5_120, publishedLabel: '1일 전' },
]
